apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rapidpro.fullname" . }}-app-config
  labels:
    {{- include "rapidpro.labels" . | nindent 4 }}
data:
  DOMAIN_NAME: {{ .Values.rapidproDomain | quote }}
  TEMBA_HOST: {{ .Values.rapidproDomain | quote }}
  MAILROOM_URL: "http://{{ include "rapidpro.fullname" . }}-mailroom:{{ .Values.mailroom.service.port }}"
  MANAGEPY_COLLECTSTATIC: {{ .Values.rapidpro.runCollectstatic | quote }}
  MANAGEPY_INIT_DB: {{ .Values.rapidpro.initDb | quote }}
  MANAGEPY_MIGRATE: {{ .Values.rapidpro.runMigrations | quote }}
  MANAGEPY_COMPRESS: {{ .Values.rapidpro.runCompress | quote }}
  CLEAR_COMPRESSOR_CACHE: {{ .Values.rapidpro.clearCompressorCache | quote }}
  AWS_STORAGE_BUCKET_NAME: {{ .Values.awsStorageBucketName | quote }}
  AWS_S3_REGION_NAME: {{ .Values.awsS3RegionName | quote }}
  AWS_ACCESS_KEY_ID: {{ .Values.awsAccessKeyId | quote }}
  EMAIL_HOST: {{ .Values.smtp.host | quote }}
  EMAIL_PORT: {{ .Values.smtp.port | quote }}
  EMAIL_USE_TLS: {{ .Values.smtp.useTls | quote }}
  DEFAULT_FROM_EMAIL: {{ .Values.smtp.defaultFromEmail | quote }}
  REDIS_URL: {{ include "rapidpro.redisUrl" . | quote }}
  ELASTICSEARCH_URL: {{ include "rapidpro.elasticsearchUrl" . | quote }}
{{- range $key, $value := .Values.rapidpro.extraEnvVars }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
