apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rapidpro.fullname" . }}-app-secrets
  labels:
    {{- include "rapidpro.labels" . | nindent 4 }}
type: Opaque
data:
  SECRET_KEY: {{ .Values.rapidpro.secretKey | b64enc | quote }}
  MAILROOM_AUTH_TOKEN: {{ .Values.mailroom.authToken | b64enc | quote }}
  EMAIL_HOST_USER: {{ .Values.smtp.username | b64enc | quote }}
  EMAIL_HOST_PASSWORD: {{ .Values.smtp.password | b64enc | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.awsSecretAccessKey | b64enc | quote }}
  DATABASE_URL: {{ include "rapidpro.databaseUrl" . | b64enc | quote }}
{{- range $key, $value := .Values.rapidpro.extraEnvSecrets }}
  {{ $key }}: {{ $value | b64enc | quote }}
{{- end }}
