apiVersion: v1
kind: Service
metadata:
  name: {{ include "rapidpro.fullname" . }}-app
  labels:
    {{- include "rapidpro.labels" . | nindent 4 }}
spec:
  type: {{ .Values.rapidpro.service.type }}
  ports:
    - port: {{ .Values.rapidpro.service.targetPort }}
      targetPort: {{ .Values.rapidpro.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "rapidpro.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: app
