apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rapidpro.fullname" . }}-indexer-config
  labels:
    {{- include "indexer.labels" . | nindent 4 }}
data:
  INDEXER_ELASTIC_URL: {{ include "rapidpro.elasticsearchUrl" . | quote }}
{{- range $key, $value := .Values.indexer.extraEnvVars }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
