apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rapidpro.fullname" . }}-indexer
  labels:
    {{- include "indexer.labels" . | nindent 4 }}
spec:
  {{- if not .Values.indexer.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "indexer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.indexer.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "indexer.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.indexer.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "rapidpro.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.indexer.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-indexer
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.indexer.image.repository }}:{{ .Values.indexer.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.indexer.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "rapidpro.fullname" . }}-indexer-config
            - secretRef:
                name: {{ include "rapidpro.fullname" . }}-indexer-secrets
          resources:
            {{- toYaml .Values.indexer.resources | nindent 12 }}
      {{- with .Values.indexer.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.indexer.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.indexer.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
