apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rapidpro.fullname" . }}-indexer-secrets
  labels:
    {{- include "indexer.labels" . | nindent 4 }}
type: Opaque
data:
  INDEXER_DB: {{ print (include "rapidpro.databaseUrl" .) "?sslmode=disable" | b64enc | quote }}
{{- range $key, $value := .Values.indexer.extraEnvSecrets }}
  {{ $key }}: {{ $value | b64enc | quote }}
{{- end }}
