{{- if .Values.archiver.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rapidpro.fullname" . }}-archiver-config
  labels:
    {{- include "archiver.labels" . | nindent 4 }}
data:
  ARCHIVER_AWS_ACCESS_KEY_ID: {{ .Values.awsAccessKeyId | quote }}
  ARCHIVER_S3_BUCKET: {{ .Values.awsStorageBucketName | quote  }}
  ARCHIVER_S3_REGION: {{ .Values.awsS3RegionName | quote }}
  ARCHIVER_S3_ENDPOINT: {{ .Values.awsS3Endpoint | quote }}
{{- range $key, $value := .Values.archiver.extraEnvVars }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{- end }}
