apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rapidpro.fullname" . }}-archiver-secrets
  labels:
    {{- include "archiver.labels" . | nindent 4 }}
type: Opaque
data:
  ARCHIVER_AWS_SECRET_ACCESS_KEY: {{ .Values.awsSecretAccessKey | b64enc | quote }}
  ARCHIVER_DB: {{ print (include "rapidpro.databaseUrl" .) "?sslmode=disable" | b64enc | quote }}
{{- range $key, $value := .Values.archiver.extraEnvSecrets }}
  {{ $key }}: {{ $value | b64enc | quote }}
{{- end }}
