apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rapidpro.fullname" . }}-courier-secrets
  labels:
    {{- include "courier.labels" . | nindent 4 }}
type: Opaque
data:
  COURIER_AWS_SECRET_ACCESS_KEY: {{ .Values.awsSecretAccessKey | b64enc | quote }}
  COURIER_DB: {{ print (include "rapidpro.databaseUrl" .) "?sslmode=disable" | b64enc | quote }}
{{- range $key, $value := .Values.courier.extraEnvSecrets }}
  {{ $key }}: {{ $value | b64enc | quote }}
{{- end }}
