apiVersion: v1
kind: Service
metadata:
  name: {{ include "rapidpro.fullname" . }}-courier
  labels:
    {{- include "courier.labels" . | nindent 4 }}
spec:
  type: {{ .Values.courier.service.type }}
  ports:
    - port: {{ .Values.courier.service.port }}
      targetPort: {{ .Values.courier.service.port }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/component: courier
    {{- include "courier.selectorLabels" . | nindent 4 }}
