apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rapidpro.fullname" . }}-mailroom-secrets
  labels:
    {{- include "mailroom.labels" . | nindent 4 }}
type: Opaque
data:
  MAILROOM_AUTH_TOKEN: {{ .Values.mailroom.authToken | b64enc | quote }}
  MAILROOM_AWS_SECRET_ACCESS_KEY: {{ .Values.awsSecretAccessKey | b64enc | quote }}
  MAILROOM_DB: {{ print (include "rapidpro.databaseUrl" .) "?sslmode=disable" | b64enc | quote }}
  MAILROOM_SMTP_SERVER: {{ include "rapidpro.smtpUrl" . | b64enc | quote }}
{{- range $key, $value := .Values.mailroom.extraEnvSecrets }}
  {{ $key }}: {{ $value | b64enc | quote }}
{{- end }}
