apiVersion: v1
kind: Service
metadata:
  name: {{ include "rapidpro.fullname" . }}-mailroom
  labels:
    {{- include "mailroom.labels" . | nindent 4 }}
spec:
  type: {{ .Values.mailroom.service.type }}
  ports:
    - port: {{ .Values.mailroom.service.port }}
      targetPort: {{ .Values.mailroom.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/component: mailroom
    {{- include "mailroom.selectorLabels" . | nindent 4 }}
